export interface Ipersonal {
    employeeId: number,
    empstatus: string,
    firstName: string,
    lastName:string,
    maritalStatus: string,
    emailaddress: string,
    internalstaff: string,
    supervisor: number,
    accountNumber: number,
    addressId: number,
    addressLine1: string,
    addressLine2: string,
    amount: number,
    backgroundCheckStatus: string,
    bankName: string,
    businessArea: string,
    city: string,
    clientName: string,
    clientcode: number,
    comments: string,
    compensationComments: string,
    compensationEffectiveDate: any,
    confirmPassword: string,
    contactnumber: number,
    country: string,
    createdby: string,
    dateOfJoining: any,
    degree: string,
    department: string,
    dob: any,
    educationenddate: any,
    educationstartdate: any,
    effectivedate: any,
    eligibleforrehire: string,
    emailId: string,
   
    emergencyName: string,
    emergencynumber: number,
    
    employementstatus: string,
   
    entity: string,
    expirationdate: any,
    
    frequency: string,
    gender: string,
    gpa: number,
    highestdegree: string,
    homeEmail: string,
    id: number,
    ifscCode: number,
    immigrationstatus: string,
   
    issuedDate: any,
    jobEffectiveDate: any,
    jobRole: string,
    degreeStartDate:any ,
    degreeEndDate: any
    lastworkingday: any,
    location: string,
    
    mobileNumber: number,
    mobilePhone: number,
    nationalId: number,
    notes: string,
    noticePeriod: string,
    overtimeEligibility: string,
    overtimerate: number,
    password: string,
    payType: string,
    payrate: number,
    payschedule: string,
    probationEndDate: any,
    probationStatus: string,
    profilePic: string,
    projectEndDate: any,
    projectName: string,
    projectStartDate: any,
    proof: string,
    reason: string,
    relationShip: string,
    reportingTo: string,
    secondaryLanguage: string,
    specialization: string,
    ssn: number,
    startdate: any,
    state: string,
    status: string,
   
    taxFileNumber: number,
    termreasonoffboard: string,
    termtypeoffboard: string,
    title: string,
    university: string,
    updatedby: string,
    userName: string,
    visaStatus: string,
    visaTypeIssuingCountry: string,
    
    workEmail: string,
    workPhone: number,
    zipCode: number,
}