export interface Ipersonal
{
    EmployeeId: number,
    Gender: string,
    FirstName: string,
    LastName: string,
    DOB: any,
    MaritalStatus: string,
    TaxFileNumber: number,
    AddressLine1: string,
    AddressLine2: string,
    City: string,
    State: string,
    Country: string,
    WorkPhone: number,
    ZipCode: number,
    MobilePhone: number,
    WorkEmail: string,
    HomeEmail: string,
    emailaddress: string,
    RelationShip: string,
    highestdegree: string,
    University: string,
    Specialization: string,
    Gpa: number,
    Educationstartdate: any,
    Educationenddate: any,
    IssuedDate: any,
    VisaStatus: string,
    VisaTypeIssuingCountry: string,
    expirationdate: any,
    status: string,
    BankName: string,
    IfscCode: number,
    AccountNumber: number,
    Proof: string,
    SecondaryLanguage: string,
    UserName: string,
    EmergencyName: string,
    empstatus: string,
    ssn: number,
    
    

}